version: "3.8"

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: mdpnewme2023
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mysql_app:
